### ISSUE TITLE
`Math.floor()` weirdness for several students

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/js-basics-intro-to-javascript-readme#7]
@gj 
I have seen several students with weird behavior happening with the `Math.floor()` test. Students will receive an error that the spy was never called, despite the fact that they are certainly calling `Math.floor()`. Interestingly, when those same students try to use `Math.floor()` in the console while the test page is loaded, `Math.floor()` does not work properly - it always returns `0`, regardless of what was passed to it. I have not been able to look into this yet, but wanted to leave a record of what is happening for now.

**Comment by gj** [comment]
@kwebster2 this sounds like an issue with the [Arithmetic Lab](https://github.com/learn-co-curriculum/js-basics-arithmetic-lab). Can you raise it over there?
